---
name: Website Theme Deployment

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        type: choice
        description: Environment
        required: true
        default: "dev"
        options:
          - dev
          - staging
          - live
      release:
        type: string
        description: Release
        required: false
        default: ""

jobs:
  deployment-run:
    uses: nationalarchives/ds-github-actions/.github/workflows/wp-theme-deploy.yml@main
    with:
      deploy-repo: "${{ github.event.repository.name }}"
      deploy-environment: "${{ inputs.deploy-environment }}"
      release: "${{ inputs.release }}"
      branch: "${{ inputs.branch }}"
...
